

# model_type: &model_type_string "model"
model_type: &model_type_string "alt_model"

defaults:
  - _self_
  - model: *model_type_string
  - events: events 


info:
  debug: false
  dir_name: null


train:
  trial_count: 10
  seed: null
  max_epochs: 7
  patience: 3
  optimizer: "AdamW"
  verbose: false
  checkpoint: 0.2
  device: "cuda:1"
  learning_rate: 3.63e-4 #3.63e-4

data:
  datasets: "noxi" #switchboard, noxi, eald
  type: "sliding"
  sample_rate: 16000
  audio_mono: true
  audio_duration: 10
  ## This config causes the data loader to swap speaker1 and 2 for half of the data, thereby break the symmetry for va, va history, and non-verbal features to prevent them from overfitting to a specific speaker configuration.
  flip_channels: true # If a single speaker model is to be trained, false is fine. # Only half the data will be used in a single speaker model.
  audio_normalize: true # If pre-processing is done beforehand, false is fine.
  audio_overlap: 9.5
  undersampling: false #discrete mode only
  oversampling: true #discrete mode only # If oversampling is set to true, the data loader will oversample the minority class to balance the dataset.
  # VAD
  vad_hz: ${model.encoder.frame_hz}
  vad_horizon: 2
  vad_history: true
  vad_history_times: [60, 30, 10, 5]
  # Data
  train_files: null
  val_files: null
  test_files: null
  batch_size: 128
  num_workers: 8
  # Label
  label_type: ${model.vap.type}
  bin_times: ${model.vap.bin_times}
  pre_frames: ${model.vap.pre_frames}
  threshold_ratio: ${model.vap.bin_threshold}

hydra:
  run:
    dir: runs
